# Generated by Django 3.2.13 on 2022-04-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('PostName', models.CharField(max_length=100)),
                ('PostDate', models.DateTimeField(auto_now_add=True)),
                ('PostUpdateDate', models.DateTimeField(auto_now=True)),
                ('PostContent', models.TextField()),
                ('PosterId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('PosterID', models.AutoField(primary_key=True, serialize=False)),
                ('PosterName', models.CharField(max_length=100)),
                ('Posts', models.IntegerField()),
            ],
        ),
    ]
